export const TOGGLE_SIDEBAR_ITEM_HOVER_STATE = 'TOGGLE_SIDEBAR_ITEM_HOVER_STATE';
export const TOGGLE_GROUP_SIDEBAR_HOVER_STATE = 'TOGGLE_GROUP_SIDEBAR_HOVER_STATE';
export const TOGGLE_GROUP_SIDEBAR_DISPLAY_STATUS = 'TOGGLE_GROUP_SIDEBAR_DISPLAY_STATUS';

